name: Other Tests
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  postgres-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

      - name: Notify
        uses: homoluctus/slatify@master
        if: github.ref == 'refs/heads/main' && failure()
        with:
          type: ${{ job.status }}
          job_name: "*postgres custom test*"
          url: ${{ secrets.BX_SLACK_BX_CHANNEL }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
